# Generated by Django 5.2.4 on 2025-07-30 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SepaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_file', models.FileField(upload_to='sepa_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(blank=True, null=True)),
                ('validation_report', models.JSONField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sepa_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
