# Generated by Django 5.2.4 on 2025-07-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SepaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_file', models.FileField(upload_to='sepa_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(blank=True, null=True)),
                ('validation_report', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
