# Generated by Django 5.2.4 on 2025-07-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sepafile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepafile',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
